# Generated by Django 4.1.7 on 2023-03-10 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_set', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activeclass',
            old_name='assigend_class',
            new_name='assigned_class',
        ),
        migrations.RenameField(
            model_name='activeclass',
            old_name='assigend_subject',
            new_name='assigned_subject',
        ),
    ]
