# Generated by Django 4.1.7 on 2023-03-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_set', '0002_rename_assigend_class_activeclass_assigned_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classstudent',
            name='mark',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
