# Generated by Django 4.1.7 on 2023-03-12 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_set', '0003_classstudent_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='classstudent',
            name='assigned_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_set.class'),
        ),
        migrations.AddField(
            model_name='classstudent',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_set.subject'),
        ),
    ]
